### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by aliraghebi** [mrgnhnt96/autoequal#1]
Hi, Are you going to migrate this package to null-safety?
Or will you accept PR if I do?

**Comment by SunnyDayDev** [comment]
Hey @arsamme!
I left the project as now I only work with native code. But I am very pleased that the library is interesting to someone) So I'll spend some time today (maybe tomorrow) to migrate the library to the null safety.
If you really want to do it by self, its ok too, I'll check your PR.

**Comment by SunnyDayDev** [comment]
@arsamme 
Please let me know if you meet any problem

**Comment by aliraghebi** [comment]
@SunnyDayDev Thanks. Everything is ok.
