### ISSUE TITLE
The getter 'element' isn't defined for the class 'InterfaceType'.

### ISSUE THREAD

**Issue by techouse** [mrgnhnt96/autoequal#14]
Looks like https://github.com/SunnyDayDev/autoequal/commit/1f4cd66138326d45c2837b3445a21d64841960c5 broke the generator when used with `analyzer: ^5.0.0`.

[`DartType.element` has been deprecated in v4.4.0](https://pub.dev/packages/analyzer/changelog#440) and [removed in v5.0.0](https://pub.dev/packages/analyzer/changelog#500). It will have to be migrated to `DartType.element2`.

I'll submit a PR later.

**Comment by SunnyDayDev** [comment]
@mrgnhnt96  FYI

If I understand correctly, @techouse has already fixed this issue before. Неre #8.

**Comment by mrgnhnt96** [comment]
Oops, sorry about that. `element2` has a deprecated annotation. Didn't realize that this was an intentional change. I'll create the PR really quick with the change 👍

**Comment by SunnyDayDev** [comment]
Hey, @techouse !

I checked the source code of analyzer and found that `element2` was deprecated in `5.2.0`.
`element` was deprecated in `4.7.0`, removed in `5.0.0` and restored in `5.2.0`. So someday `element2` will be removed. In this case, do we need to support it?

```dart
  @Deprecated('Use element instead')
  @override
  InterfaceElement get element2;
```

**Comment by techouse** [comment]
Yeah, it's a mess 🙈, however, I doubt that they will remove `element2` before `v6.0.0` and you don't really want to force people to `analyzer: ^5.2.0` because of a deprecation.

**Comment by mrgnhnt96** [comment]
@techouse could you provide us with a minimal code example? I would like to add this to our tests to avoid breaking this in future versions

**Comment by techouse** [comment]
It's kinda hard to test for a function that got removed. I tried to make something similar. It's just not a thing in Dart as it is in JS.

**Comment by mrgnhnt96** [comment]
All good, in your project you're using `analyzer: ^5.0.0` and that is what broke your builder? 

It might be worth it to update our analyzer dependency to latest. In the meantime, we will fix this in the next version with the current versioning.

**Comment by techouse** [comment]
Correct.
