### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by mrgnhnt96** [mrgnhnt96/autoequal#17]
Hey @SunnyDayDev 👋 

I thought we'd make an issue to transfer ownership, that way we can communicate about what actions are taking place and when.

I accepted the invite to the publishers on pub.dev. You (or I) can transfer the ownership of the package whenever you'd like.

For the repository, I haven't gotten any invites yet to transfer the ownership of the repo.

If there is anything that you need me to do, please let me know.

**Comment by SunnyDayDev** [comment]
Hey @mrgnhnt96 

I invited you as publisher to sunnyday.dev few days ago, so you can transfer packages. After it we'll transfer the repo

**Comment by SunnyDayDev** [comment]
Hey @mrgnhnt96 !

You have to transfer packages on pub.dev, only you are member of both publishers.

**Comment by SunnyDayDev** [comment]
Now I'll send an invite to transfer the repo

**Comment by SunnyDayDev** [comment]
I tried to transfer the repo and got the error

<img width="282" alt="transfer_error" src="https://user-images.githubusercontent.com/11307625/199643068-75ae470c-2c60-4a44-8194-ad4c97e0d87a.png">

**Comment by SunnyDayDev** [comment]
In this case, do we really need to transfer the repo?

I can archive my repo with notification and links to your, and you'll continue develop in your fork. Just update `homepage` to you repo in `pubspec.yml`.

**Comment by mrgnhnt96** [comment]
Okay, I'll transfer over the package this morning on pub.dev. 

It would be best to transfer the repo to maintain history of the commits, PRs, and issues. I just deleted the repo from my account, so you can try to transfer it again

**Comment by SunnyDayDev** [comment]
Hey @mrgnhnt96!

You have transferred the package, is it right? Can I remove you from publishers of sunnyday.dev?

**Comment by mrgnhnt96** [comment]
Yup! I transferred it earlier today, looks like it propagating correctly! You can remove me from the publishers now.

The repo was also successfully transferred over to me. So the transfer is complete now!

Thanks for entrusting me with this!

**Comment by SunnyDayDev** [comment]
Yeah! That's great!
I'm sure it's in the right hands)
